// source: CustomerDetailsAndWallet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.io.awesome.proto.CustomerDetails', null, global);
goog.exportSymbol('proto.io.awesome.proto.Wallet', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.awesome.proto.Wallet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.awesome.proto.Wallet.repeatedFields_, null);
};
goog.inherits(proto.io.awesome.proto.Wallet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.awesome.proto.Wallet.displayName = 'proto.io.awesome.proto.Wallet';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.awesome.proto.CustomerDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.awesome.proto.CustomerDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.awesome.proto.CustomerDetails.displayName = 'proto.io.awesome.proto.CustomerDetails';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.awesome.proto.Wallet.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.awesome.proto.Wallet.prototype.toObject = function(opt_includeInstance) {
  return proto.io.awesome.proto.Wallet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.awesome.proto.Wallet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.Wallet.toObject = function(includeInstance, msg) {
  var f, obj = {
    privatekeyhex: jspb.Message.getFieldWithDefault(msg, 1, ""),
    initializationvectorhex: jspb.Message.getFieldWithDefault(msg, 2, ""),
    encrypted: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    publickeyhex: jspb.Message.getFieldWithDefault(msg, 4, ""),
    id: jspb.Message.getFieldWithDefault(msg, 5, ""),
    id2: jspb.Message.getFieldWithDefault(msg, 6, ""),
    transactionoutputsList: msg.getTransactionoutputsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.awesome.proto.Wallet}
 */
proto.io.awesome.proto.Wallet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.awesome.proto.Wallet;
  return proto.io.awesome.proto.Wallet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.awesome.proto.Wallet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.awesome.proto.Wallet}
 */
proto.io.awesome.proto.Wallet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrivatekeyhex(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInitializationvectorhex(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEncrypted(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublickeyhex(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setId2(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTransactionoutputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.Wallet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.awesome.proto.Wallet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.awesome.proto.Wallet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.Wallet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrivatekeyhex();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInitializationvectorhex();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEncrypted();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPublickeyhex();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getId2();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTransactionoutputsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      7,
      f
    );
  }
};


/**
 * optional string privateKeyHex = 1;
 * @return {string}
 */
proto.io.awesome.proto.Wallet.prototype.getPrivatekeyhex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setPrivatekeyhex = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string initializationVectorHex = 2;
 * @return {string}
 */
proto.io.awesome.proto.Wallet.prototype.getInitializationvectorhex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setInitializationvectorhex = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool encrypted = 3;
 * @return {boolean}
 */
proto.io.awesome.proto.Wallet.prototype.getEncrypted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setEncrypted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string publicKeyHex = 4;
 * @return {string}
 */
proto.io.awesome.proto.Wallet.prototype.getPublickeyhex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setPublickeyhex = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string id = 5;
 * @return {string}
 */
proto.io.awesome.proto.Wallet.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string id2 = 6;
 * @return {string}
 */
proto.io.awesome.proto.Wallet.prototype.getId2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setId2 = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated bytes transactionOutputs = 7;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.io.awesome.proto.Wallet.prototype.getTransactionoutputsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * repeated bytes transactionOutputs = 7;
 * This is a type-conversion wrapper around `getTransactionoutputsList()`
 * @return {!Array<string>}
 */
proto.io.awesome.proto.Wallet.prototype.getTransactionoutputsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getTransactionoutputsList()));
};


/**
 * repeated bytes transactionOutputs = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTransactionoutputsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.io.awesome.proto.Wallet.prototype.getTransactionoutputsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTransactionoutputsList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.setTransactionoutputsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.addTransactionoutputs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.io.awesome.proto.Wallet} returns this
 */
proto.io.awesome.proto.Wallet.prototype.clearTransactionoutputsList = function() {
  return this.setTransactionoutputsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.awesome.proto.CustomerDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.io.awesome.proto.CustomerDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.awesome.proto.CustomerDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.CustomerDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    telephone: jspb.Message.getFieldWithDefault(msg, 3, ""),
    email: jspb.Message.getFieldWithDefault(msg, 4, ""),
    username: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.awesome.proto.CustomerDetails}
 */
proto.io.awesome.proto.CustomerDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.awesome.proto.CustomerDetails;
  return proto.io.awesome.proto.CustomerDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.awesome.proto.CustomerDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.awesome.proto.CustomerDetails}
 */
proto.io.awesome.proto.CustomerDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTelephone(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.CustomerDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.awesome.proto.CustomerDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.awesome.proto.CustomerDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.CustomerDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTelephone();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.io.awesome.proto.CustomerDetails.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.CustomerDetails} returns this
 */
proto.io.awesome.proto.CustomerDetails.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.io.awesome.proto.CustomerDetails.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.CustomerDetails} returns this
 */
proto.io.awesome.proto.CustomerDetails.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string telephone = 3;
 * @return {string}
 */
proto.io.awesome.proto.CustomerDetails.prototype.getTelephone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.CustomerDetails} returns this
 */
proto.io.awesome.proto.CustomerDetails.prototype.setTelephone = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string email = 4;
 * @return {string}
 */
proto.io.awesome.proto.CustomerDetails.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.CustomerDetails} returns this
 */
proto.io.awesome.proto.CustomerDetails.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string userName = 5;
 * @return {string}
 */
proto.io.awesome.proto.CustomerDetails.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.CustomerDetails} returns this
 */
proto.io.awesome.proto.CustomerDetails.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.io.awesome.proto);
