// source: RequestResponse.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.io.awesome.proto.RequestResponse', null, global);
goog.exportSymbol('proto.io.awesome.proto.RequestResponse.Request', null, global);
goog.exportSymbol('proto.io.awesome.proto.RequestResponse.Response', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.awesome.proto.RequestResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.awesome.proto.RequestResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.awesome.proto.RequestResponse.displayName = 'proto.io.awesome.proto.RequestResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.awesome.proto.RequestResponse.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.awesome.proto.RequestResponse.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.awesome.proto.RequestResponse.Request.displayName = 'proto.io.awesome.proto.RequestResponse.Request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.awesome.proto.RequestResponse.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.awesome.proto.RequestResponse.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.io.awesome.proto.RequestResponse.Response.displayName = 'proto.io.awesome.proto.RequestResponse.Response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.awesome.proto.RequestResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.io.awesome.proto.RequestResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.awesome.proto.RequestResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    request: (f = msg.getRequest()) && proto.io.awesome.proto.RequestResponse.Request.toObject(includeInstance, f),
    response: (f = msg.getResponse()) && proto.io.awesome.proto.RequestResponse.Response.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.awesome.proto.RequestResponse}
 */
proto.io.awesome.proto.RequestResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.awesome.proto.RequestResponse;
  return proto.io.awesome.proto.RequestResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.awesome.proto.RequestResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.awesome.proto.RequestResponse}
 */
proto.io.awesome.proto.RequestResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.awesome.proto.RequestResponse.Request;
      reader.readMessage(value,proto.io.awesome.proto.RequestResponse.Request.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 2:
      var value = new proto.io.awesome.proto.RequestResponse.Response;
      reader.readMessage(value,proto.io.awesome.proto.RequestResponse.Response.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.awesome.proto.RequestResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.awesome.proto.RequestResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.io.awesome.proto.RequestResponse.Request.serializeBinaryToWriter
    );
  }
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.awesome.proto.RequestResponse.Response.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.io.awesome.proto.RequestResponse.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.awesome.proto.RequestResponse.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    jsonrequest: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: msg.getData_asB64(),
    entries: msg.getEntries_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.awesome.proto.RequestResponse.Request}
 */
proto.io.awesome.proto.RequestResponse.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.awesome.proto.RequestResponse.Request;
  return proto.io.awesome.proto.RequestResponse.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.awesome.proto.RequestResponse.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.awesome.proto.RequestResponse.Request}
 */
proto.io.awesome.proto.RequestResponse.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonrequest(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEntries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.awesome.proto.RequestResponse.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.awesome.proto.RequestResponse.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJsonrequest();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getEntries_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string jsonRequest = 1;
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getJsonrequest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.RequestResponse.Request} returns this
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.setJsonrequest = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes data = 2;
 * @return {!(string|Uint8Array)}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.io.awesome.proto.RequestResponse.Request} returns this
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes entries = 3;
 * @return {!(string|Uint8Array)}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getEntries = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes entries = 3;
 * This is a type-conversion wrapper around `getEntries()`
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getEntries_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEntries()));
};


/**
 * optional bytes entries = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEntries()`
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.getEntries_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEntries()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.io.awesome.proto.RequestResponse.Request} returns this
 */
proto.io.awesome.proto.RequestResponse.Request.prototype.setEntries = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.io.awesome.proto.RequestResponse.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.awesome.proto.RequestResponse.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    jsonresponse: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: msg.getData_asB64(),
    entries: msg.getEntries_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.awesome.proto.RequestResponse.Response}
 */
proto.io.awesome.proto.RequestResponse.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.awesome.proto.RequestResponse.Response;
  return proto.io.awesome.proto.RequestResponse.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.awesome.proto.RequestResponse.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.awesome.proto.RequestResponse.Response}
 */
proto.io.awesome.proto.RequestResponse.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonresponse(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEntries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.awesome.proto.RequestResponse.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.awesome.proto.RequestResponse.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.awesome.proto.RequestResponse.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJsonresponse();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getEntries_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string jsonResponse = 1;
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getJsonresponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.io.awesome.proto.RequestResponse.Response} returns this
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.setJsonresponse = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes data = 2;
 * @return {!(string|Uint8Array)}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.io.awesome.proto.RequestResponse.Response} returns this
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes entries = 3;
 * @return {!(string|Uint8Array)}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getEntries = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes entries = 3;
 * This is a type-conversion wrapper around `getEntries()`
 * @return {string}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getEntries_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEntries()));
};


/**
 * optional bytes entries = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEntries()`
 * @return {!Uint8Array}
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.getEntries_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEntries()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.io.awesome.proto.RequestResponse.Response} returns this
 */
proto.io.awesome.proto.RequestResponse.Response.prototype.setEntries = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional Request request = 1;
 * @return {?proto.io.awesome.proto.RequestResponse.Request}
 */
proto.io.awesome.proto.RequestResponse.prototype.getRequest = function() {
  return /** @type{?proto.io.awesome.proto.RequestResponse.Request} */ (
    jspb.Message.getWrapperField(this, proto.io.awesome.proto.RequestResponse.Request, 1));
};


/**
 * @param {?proto.io.awesome.proto.RequestResponse.Request|undefined} value
 * @return {!proto.io.awesome.proto.RequestResponse} returns this
*/
proto.io.awesome.proto.RequestResponse.prototype.setRequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.awesome.proto.RequestResponse} returns this
 */
proto.io.awesome.proto.RequestResponse.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.awesome.proto.RequestResponse.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Response response = 2;
 * @return {?proto.io.awesome.proto.RequestResponse.Response}
 */
proto.io.awesome.proto.RequestResponse.prototype.getResponse = function() {
  return /** @type{?proto.io.awesome.proto.RequestResponse.Response} */ (
    jspb.Message.getWrapperField(this, proto.io.awesome.proto.RequestResponse.Response, 2));
};


/**
 * @param {?proto.io.awesome.proto.RequestResponse.Response|undefined} value
 * @return {!proto.io.awesome.proto.RequestResponse} returns this
*/
proto.io.awesome.proto.RequestResponse.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.io.awesome.proto.RequestResponse} returns this
 */
proto.io.awesome.proto.RequestResponse.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.io.awesome.proto.RequestResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.io.awesome.proto);
